-- =============================================================================
-- FILE:    04_sponsor_roi_chain.sql
-- PURPOSE: Multi-step CTE chain to calculate sponsor ROI by combining
--          deal value, viewership exposure, ticket revenue influence,
--          and team performance reach
-- =============================================================================

USE EsportsLeague;
GO

-- =============================================================================
-- QUERY 1: Full sponsor ROI pipeline
--          Step 1: sponsorship deal values by sponsor
--          Step 2: viewership exposure from sponsored tournaments
--          Step 3: ticket revenue from sponsored events
--          Step 4: team reach (fans + standings) for team sponsors
--          Step 5: composite ROI score per sponsor
-- =============================================================================

WITH sponsor_deals AS (
    -- Step 1: total committed value per sponsor across all active/expired deals
    SELECT
        sp.sponsor_id,
        s.company_name,
        s.industry,
        s.tier                                      AS sponsor_tier,
        COUNT(*)                                    AS total_deals,
        SUM(sp.deal_value)                          AS total_deal_value,
        SUM(CASE WHEN sp.team_id IS NOT NULL
                 THEN sp.deal_value ELSE 0 END)     AS team_deal_value,
        SUM(CASE WHEN sp.tournament_id IS NOT NULL
                 THEN sp.deal_value ELSE 0 END)     AS tournament_deal_value,
        COUNT(DISTINCT sp.team_id)                  AS teams_sponsored,
        COUNT(DISTINCT sp.tournament_id)            AS tournaments_sponsored
    FROM ops.sponsorship sp
    JOIN ops.sponsor     s ON s.sponsor_id = sp.sponsor_id
    WHERE sp.status IN ('Active', 'Expired')
    GROUP BY sp.sponsor_id, s.company_name, s.industry, s.tier
),
tournament_viewership AS (
    -- Step 2: total viewership hours generated by each tournament
    --         aggregated up to the sponsoring company
    SELECT
        sp.sponsor_id,
        SUM(vl.peak_viewers)                        AS total_peak_viewers,
        SUM(vl.avg_viewers)                         AS total_avg_viewers,
        SUM(vl.stream_duration_min)                 AS total_stream_minutes,
        SUM(vl.chat_messages)                       AS total_chat_messages,
        -- Estimated viewer-hours (avg_viewers * hours)
        SUM(
            CAST(vl.avg_viewers AS BIGINT)
            * CAST(COALESCE(vl.stream_duration_min, 0) AS BIGINT)
            / 60
        )                                           AS total_viewer_hours,
        COUNT(DISTINCT vl.log_id)                   AS broadcast_slots
    FROM ops.sponsorship       sp
    JOIN comp.tournament       tn ON tn.tournament_id = sp.tournament_id
    JOIN ops.broadcast_rights  br ON br.tournament_id = tn.tournament_id
    JOIN ops.viewership_log    vl ON vl.rights_id     = br.rights_id
    WHERE sp.tournament_id IS NOT NULL
      AND vl.match_id IS NOT NULL
    GROUP BY sp.sponsor_id
),
event_ticket_revenue AS (
    -- Step 3: ticket revenue from events within sponsored tournaments
    SELECT
        sp.sponsor_id,
        SUM(o.total_amount)                         AS associated_ticket_revenue,
        SUM(o.quantity)                             AS associated_tickets_sold,
        COUNT(DISTINCT e.event_id)                  AS associated_events
    FROM ops.sponsorship   sp
    JOIN comp.tournament   tn  ON tn.tournament_id = sp.tournament_id
    JOIN ops.event         e   ON e.tournament_id  = tn.tournament_id
    JOIN ops.ticket_tier   tt  ON tt.event_id      = e.event_id
    JOIN ops.ticket_order  o   ON o.tier_id        = tt.tier_id
    WHERE sp.tournament_id IS NOT NULL
      AND o.status = 'Confirmed'
    GROUP BY sp.sponsor_id
),
team_fan_reach AS (
    -- Step 4: fan base of sponsored teams + their standings performance
    SELECT
        sp.sponsor_id,
        COUNT(DISTINCT f.fan_id)                    AS total_fans_reached,
        AVG(CAST(ts.points AS FLOAT))               AS avg_team_points,
        SUM(ts.wins)                                AS total_team_wins
    FROM ops.sponsorship    sp
    JOIN comp.team          t   ON t.team_id        = sp.team_id
    JOIN ops.fan            f   ON f.favourite_team_id = t.team_id
    LEFT JOIN comp.team_standing ts ON ts.team_id   = t.team_id
    WHERE sp.team_id IS NOT NULL
    GROUP BY sp.sponsor_id
),
roi_composite AS (
    -- Step 5: combine all signals into a single ROI score
    SELECT
        sd.sponsor_id,
        sd.company_name,
        sd.industry,
        sd.sponsor_tier,
        sd.total_deals,
        sd.total_deal_value,
        sd.team_deal_value,
        sd.tournament_deal_value,
        sd.teams_sponsored,
        sd.tournaments_sponsored,

        -- Viewership metrics
        COALESCE(tv.total_peak_viewers, 0)          AS total_peak_viewers,
        COALESCE(tv.total_viewer_hours, 0)          AS total_viewer_hours,
        COALESCE(tv.total_chat_messages, 0)         AS total_chat_messages,
        COALESCE(tv.broadcast_slots, 0)             AS broadcast_slots,

        -- Ticket revenue association
        COALESCE(etr.associated_ticket_revenue, 0)  AS associated_ticket_revenue,
        COALESCE(etr.associated_tickets_sold, 0)    AS associated_tickets_sold,
        COALESCE(etr.associated_events, 0)          AS associated_events,

        -- Fan reach
        COALESCE(tfr.total_fans_reached, 0)         AS total_fans_reached,
        COALESCE(tfr.avg_team_points, 0)            AS avg_sponsored_team_points,

        -- CPM (cost per thousand viewers)
        ROUND(
            sd.total_deal_value * 1000.0
            / NULLIF(COALESCE(tv.total_peak_viewers, 0), 0),
        2)                                          AS cpm_peak_viewers,

        -- Cost per viewer-hour (brand exposure efficiency)
        ROUND(
            sd.total_deal_value
            / NULLIF(COALESCE(tv.total_viewer_hours, 0), 0),
        4)                                          AS cost_per_viewer_hour,

        -- Cost per fan reached (team sponsorships)
        ROUND(
            sd.team_deal_value
            / NULLIF(COALESCE(tfr.total_fans_reached, 0), 0),
        2)                                          AS cost_per_fan,

        -- Composite ROI score (higher = better value for spend)
        -- Normalised signals: viewer hours per $1000 spend + fans per $1000 + tickets per $1000
        ROUND(
            (COALESCE(tv.total_viewer_hours, 0) / NULLIF(sd.total_deal_value / 1000.0, 0))
          + (COALESCE(tfr.total_fans_reached, 0)  / NULLIF(sd.total_deal_value / 1000.0, 0)) * 10
          + (COALESCE(etr.associated_tickets_sold, 0) / NULLIF(sd.total_deal_value / 1000.0, 0)) * 5,
        2)                                          AS roi_composite_score
    FROM sponsor_deals          sd
    LEFT JOIN tournament_viewership  tv  ON tv.sponsor_id  = sd.sponsor_id
    LEFT JOIN event_ticket_revenue   etr ON etr.sponsor_id = sd.sponsor_id
    LEFT JOIN team_fan_reach         tfr ON tfr.sponsor_id = sd.sponsor_id
)
SELECT
    company_name,
    industry,
    sponsor_tier,
    total_deals,
    total_deal_value,
    teams_sponsored,
    tournaments_sponsored,
    total_peak_viewers,
    total_viewer_hours,
    total_fans_reached,
    associated_ticket_revenue,
    cpm_peak_viewers,
    cost_per_viewer_hour,
    cost_per_fan,
    roi_composite_score,
    -- Portfolio rank by ROI
    RANK() OVER (ORDER BY roi_composite_score DESC) AS roi_rank,
    -- Tier rank by deal value
    RANK() OVER (
        PARTITION BY sponsor_tier
        ORDER BY total_deal_value DESC
    )                                               AS rank_within_tier
FROM roi_composite
ORDER BY roi_rank;
GO

-- =============================================================================
-- QUERY 2: Sponsorship gap analysis
--          Which tournaments and teams have NO sponsorship coverage?
--          Uses NOT EXISTS anti-join pattern inside a CTE
-- =============================================================================

WITH all_tournaments AS (
    SELECT
        tn.tournament_id,
        tn.name                                     AS tournament_name,
        tn.prize_pool,
        tn.status,
        l.name                                      AS league_name,
        g.name                                      AS game_name,
        r.name                                      AS region_name
    FROM comp.tournament tn
    JOIN comp.league     l ON l.league_id  = tn.league_id
    JOIN comp.game       g ON g.game_id    = l.game_id
    JOIN comp.region     r ON r.region_id  = l.region_id
),
sponsored_tournaments AS (
    SELECT DISTINCT tournament_id
    FROM ops.sponsorship
    WHERE tournament_id IS NOT NULL
      AND status IN ('Active', 'Expired')
),
all_active_teams AS (
    SELECT
        t.team_id,
        t.name                                      AS team_name,
        r.name                                      AS region_name,
        COUNT(DISTINCT p.player_id)                 AS roster_size,
        SUM(c.salary_monthly)                       AS monthly_wage_bill
    FROM comp.team     t
    JOIN comp.region   r ON r.region_id = t.region_id
    LEFT JOIN comp.player   p ON p.team_id = t.team_id AND p.status = 'Active'
    LEFT JOIN comp.contract c ON c.team_id = t.team_id AND c.status  = 'Active'
    WHERE t.is_active = 1
    GROUP BY t.team_id, t.name, r.name
),
sponsored_teams AS (
    SELECT DISTINCT team_id
    FROM ops.sponsorship
    WHERE team_id IS NOT NULL
      AND status = 'Active'
)
-- Unsponsored tournaments
SELECT
    'Tournament'                                    AS entity_type,
    at2.tournament_name                             AS name,
    at2.game_name,
    at2.region_name,
    at2.status,
    CAST(at2.prize_pool AS NVARCHAR)                AS additional_info
FROM all_tournaments at2
WHERE NOT EXISTS (
    SELECT 1 FROM sponsored_tournaments st
    WHERE st.tournament_id = at2.tournament_id
)
AND at2.status IN ('Scheduled', 'Ongoing', 'Completed')

UNION ALL

-- Unsponsored active teams
SELECT
    'Team',
    aat.team_name,
    NULL,
    aat.region_name,
    'Active',
    CONCAT('Roster: ', aat.roster_size, ' | Wage bill: $', aat.monthly_wage_bill)
FROM all_active_teams aat
WHERE NOT EXISTS (
    SELECT 1 FROM sponsored_teams spt
    WHERE spt.team_id = aat.team_id
)
ORDER BY entity_type, name;
GO

PRINT '04_sponsor_roi_chain.sql loaded.';
GO
